[options]
girs_dir = "gir-files"
library = "GObject"
version = "2.0"
min_cfg_version = "2.42"
target_path = "."
auto_path = "src/gobject/auto"
work_mode = "normal"
single_version_file = true
deprecate_by_min_version = true
trust_return_value_nullability = true
girs_directories = ["../gir-files"]

generate = [
    "GObject.BindingFlags",
    "GObject.SignalFlags",
]

ignore = [
]

manual = [
    "GObject.Object",
    "GObject.Value",
    "GObject.ParamFlags",
]

[[object]]
name = "GObject.Binding"
status = "generate"
trait = false
concurrency = "send+sync"
    [[object.function]]
    name = "get_source"
    # Not thread-safe, see https://gitlab.gnome.org/GNOME/glib/-/merge_requests/1745
    # Using the GObject properties will be automatically safe with GLib 2.68.
    ignore = true
    [[object.function]]
    name = "get_target"
    # Not thread-safe, see https://gitlab.gnome.org/GNOME/glib/-/merge_requests/1745
    # Using the GObject properties will be automatically safe with GLib 2.68.
    ignore = true
    [[object.property]]
    name = "source"
    # So we can implement setter/getter with the correct name
    ignore = true
    [[object.property]]
    name = "target"
    # So we can implement setter/getter with the correct name
    ignore = true

[[object]]
name = "GObject.*"
status = "ignore"
